name: Run `make test`

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  make-test:
    name: Run `make test`
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1

      - name: Run `make test`
        run: make test
